In [1]:
import numpy as np

## DataTypes & Attributes

In [6]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])
a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(2, 3)

In [13]:
a3.shape

(2, 3, 3)

In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [16]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [17]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
# Create the dataframe from Numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.0,3.3
1,4.0,5.0,6.5


## Creating NumPy Arrays

In [19]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [20]:
sample_array.dtype

dtype('int64')

In [23]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
range_array = np.arange(0,10,2) # start, stop, steps
range_array

array([0, 2, 4, 6, 8])

In [ ]:
random_array = np.random.randint(0,10, size = (3,5)) #Generates random numbers between 0 and 9, shaped into 3 rows and 5 columns
random_array

array([[7, 4, 7, 3, 1],
       [4, 0, 9, 7, 3],
       [4, 4, 1, 1, 4]], dtype=int32)

In [3]:
import numpy as np

In [4]:
random_array = np.random.randint(0,10, size = (3,5))
random_array

array([[5, 7, 4, 1, 9],
       [0, 8, 9, 9, 4],
       [5, 0, 1, 9, 0]], dtype=int32)

In [5]:
random_array.size

15

In [6]:
random_array.shape

(3, 5)

In [ ]:
random_array_2 = np.random.random((3,5)) # noticed that random only take two arguments given that they also have their parenthesis.
random_array_2

array([[0.48489074, 0.38380022, 0.72873292, 0.96274188, 0.20513492],
       [0.5114026 , 0.90858463, 0.99959812, 0.81826151, 0.98946395],
       [0.49883998, 0.5666534 , 0.43649953, 0.05165631, 0.900968  ]])

In [10]:
random_array_2.shape

(3,)

In [ ]:
random_array_3 = np.random.rand(5,3) #rand toook 2 arguments.
random_array_3

array([[0.09037134, 0.7855704 , 0.62561534],
       [0.60695233, 0.93050265, 0.8061135 ],
       [0.84559641, 0.02084535, 0.87859556],
       [0.18705619, 0.74253338, 0.19802924],
       [0.51410354, 0.29845522, 0.01602508]])

In [ ]:
# Pseudo-random numbers
# np.random.seed()
np.random.seed(seed = 0) # keep the random arrangement still
random_array_4 = np.random.randint(10, size =(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [22]:
random_array_4.shape

(5, 3)

In [ ]:
np.random.seed(7)
random_array_5 = np.random.random((5,3)) # function generates a grid of random decimal numbers (fractions) instead of whole numbers.
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [26]:
random_array_5.shape

(5, 3)

## Viewing arrays and matrices 

In [28]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [30]:
random_array_2[0]

array([0.48489074, 0.38380022, 0.72873292, 0.96274188, 0.20513492])

In [32]:
random_array_3[:2, :2]

array([[0.09037134, 0.7855704 ],
       [0.60695233, 0.93050265]])

In [43]:
np.random.seed(7)
a4 =np.random.randint(10, size = (2, 3, 4, 5))
a4

array([[[[4, 9, 6, 3, 3],
         [7, 7, 9, 7, 8],
         [9, 8, 7, 6, 4],
         [0, 7, 0, 7, 6]],

        [[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]]],


       [[[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]],

        [[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]]]], dtype=int32)

In [34]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [38]:
# Get the first 4 number of the inner most arrays
a4[:, :, :, :5]

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]], dtype=int32)