In [1]:
import numpy as np

## DataTypes & Attributes

In [6]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])
a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(2, 3)

In [13]:
a3.shape

(2, 3, 3)

In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [16]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [17]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
# Create the dataframe from Numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.0,3.3
1,4.0,5.0,6.5


## Creating NumPy Arrays

In [19]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [20]:
sample_array.dtype

dtype('int64')

In [23]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0,10, size = (3,5))
random_array

array([[7, 4, 7, 3, 1],
       [4, 0, 9, 7, 3],
       [4, 4, 1, 1, 4]], dtype=int32)